### ISSUE TITLE
Support sddm qt6

### ISSUE THREAD

**Issue by arkhan** [plattfot/guix-simplyblack-sddm#1]

**Comment by plattfot** [comment]
I'll see what I can do in the coming week.

**Comment by plattfot** [comment]
Sorry, did get much work on it last week. I did setup an environment in which I can evaluate the theme. What issues are you seeing when trying to use this theme with qt6? Just so I know I can reproduce the right issues on my side.

Thanks

**Comment by RJSent** [comment]
I observe the theme failing to apply. SDDM falls back to a default theme. Here's the log:

```
[16:31:38.695] (II) DAEMON: Loading theme configuration from "/gnu/store/vvdgqz68b7hjysyxvx4jgrfs9n8l161a-guix-simplyblack-sddm-theme-0.1/share/sddm/themes/guix-simplyblack-sddm/theme.conf"
[16:31:38.695] (WW) DAEMON: The theme at "/gnu/store/vvdgqz68b7hjysyxvx4jgrfs9n8l161a-guix-simplyblack-sddm-theme-0.1/share/sddm/themes/guix-simplyblack-sddm" requires missing "/gnu/store/m08apz2d9z3xf4y7690y8sgzv4d3clvh-sddm-0.21.0/bin/sddm-greeter" . Using fallback theme.
[16:31:38.695] (II) DAEMON: Loaded empty theme configuration
```

Unfortunately I don't know what is required to migrate a theme to QT6.

**Comment by plattfot** [comment]
Hmm, ok not the same error I get when I testing it with the `sddm-greeter-qt6 --test-mode`.

Thanks for the log though.

> `...guix-simplyblack-sddm" requires missing "...bin/sddm-greeter" `

Might be a good hint of what's wrong.

> Unfortunately I don't know what is required to migrate a theme to QT6.

Me neither :sweat_smile: . Fortunately guix still has `sddm-qt5` which I can test with and there the theme looks good. On qt6 the background is white. So with that I should hopefully figure out why it's broken and fix it. I have allocated some time this weekend to work on this.

**Comment by plattfot** [comment]
Ok made some changes so now at least it looks good when I run it in test mode for qt 5.  Can someone see if #2 fixes it for you?

I don't see `guix system reconfiguration` has support for transformers from the cli. But I think you should be able to do something like this in your system configuration:
```
(define test-guix-simplyblack-theme-qt6
  (options->transformation
   '((with-branch . "guix-simplyblack-theme=qt6_support"))))

;; Replace guix-simplyblack-theme where you specify it in your `operating-system` with:
(test-guix-simplyblack-theme-qt6 guix-simplyblack-theme)

```
Don't forget to include the `(guix transformations)` module.

Edit: wording

**Comment by plattfot** [comment]
Accidentally closed this when I merged the Qt6 support. Reopening this  until it lands in guix's main channel: see [72812](https://issues.guix.gnu.org/issue/72812). Also noticed that the colors on the buttons is not behaving correctly in Qt6. That might be a bug in SDDM though. I'll open an issue on their side and check.

**Comment by plattfot** [comment]
It landed in guix's main channel a week or so ago, closing.
